[package]
name = "material-wm"
version = "0.1.0"
edition = "2021"

[profile.dev]
opt-level = 1
debug = 1

[profile.release]
opt-level = 3
lto = "thin"
codegen-units = 1

[dependencies]
smithay = { version = "0.7", features = [
    "backend_winit",
    "backend_drm",
    "backend_libinput",
    "backend_udev",
    "backend_egl",
    "backend_gbm",
    "renderer_gl",
    "xwayland",
    "desktop",
] }
wayland-server = "0.31"
xkbcommon = "0.8"
serde = { version = "1.0", features = ["derive"] }
toml = "0.8"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
fontdue = "0.9"
rodio = { version = "0.20", default-features = false, features = ["wav"] }
zbus = "5"
image = { version = "0.25", default-features = false, features = ["jpeg", "png"] }
libc = "0.2"
